[package]
name = "pallet-oracle"
version = "0.1.0"
description = ""
edition = "2021"
license = "Apache-2.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { features = [
	"derive",
], workspace = true }
scale-info = { features = [
	"derive",
], workspace = true }
frame-support.workspace = true
frame-system.workspace = true
log.workspace = true
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"scale-info/std",
	"log/std",
	"serde_json/std",
	"serde/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
]
